// TODO: 실제 API 연동 시 제거

import type { FAQItem, FAQTopic } from "@/types/api/faq";
import type { Source } from "@/types/chat";

export const MOCK_FAQ_TOPICS: FAQTopic[] = [
  { topic: "all", label: "전체" },
  { topic: "academic", label: "학사" },
  { topic: "graduation", label: "졸업" },
  { topic: "enrollment_status", label: "휴학·복학·자퇴" },
  { topic: "scholarship", label: "장학" },
  { topic: "registration", label: "등록·학적" },
  { topic: "curriculum", label: "전공·교과" },
  { topic: "career", label: "취업·현장실습" },
  { topic: "event", label: "행사·특강" },
  { topic: "other", label: "기타" },
];

export const MOCK_FAQ_ITEMS: FAQItem[] = [
  {
    faqId: "1",
    question: "성적우수 장학금 기준은 무엇인가요?",
    answer: "직전 학기 12학점 이상 이수 후 GPA 3.5 이상이면 신청 자격이 생깁니다. 우등 장학금(GPA 3.8↑)은 학과 정원의 5%, 성적 장학금은 15% 이내에서 지급합니다. (장학금 규정 제8조)",
    topic: "scholarship",
    createdAt: "2026-04-08T09:05:00Z",
    helpful: 57, notHelpful: 3, isNew: true,
    sources: [
      { documentId: 4, documentTitle: "2026-1학기 SW학부 성적우수 장학금 안내", page: 2 },
      { documentId: 7, documentTitle: "SW중심대학 장학금 신청 안내", page: 1 },
    ] satisfies Source[],
  },
  {
    faqId: "2",
    question: "수강신청 최대 학점은 몇 학점인가요?",
    answer: "일반적으로 학기당 최대 19학점까지 신청 가능합니다. 단, 직전 학기 GPA가 4.0 이상인 경우에는 22학점까지 신청할 수 있습니다. (학칙 제28조)",
    topic: "academic",
    createdAt: "2026-04-08T08:12:00Z",
    helpful: 42, notHelpful: 2, isNew: true,
    sources: [
      { documentId: 12, documentTitle: "국민대학교 학칙 전문 (2026년 개정)", page: 28 },
      { documentId: 20, documentTitle: "SW융합대학 교육과정표 (2026학년도)", page: 5 },
    ] satisfies Source[],
  },
  {
    faqId: "3",
    question: "이번 학기 휴학 신청 기간이 언제인가요?",
    answer: "2026학년도 1학기 휴학 신청 기간은 3월 3일(월)부터 3월 14일(금)까지입니다. KLAS → 학적 → 휴복학 신청 메뉴에서 온라인으로 신청하실 수 있습니다.",
    topic: "enrollment_status",
    createdAt: "2026-04-08T07:55:00Z",
    helpful: 89, notHelpful: 1, isNew: true,
  },
  {
    faqId: "4",
    question: "수강 정정 기간에 과목을 추가·취소할 수 있나요?",
    answer: "네, 개강 후 1주일 이내의 수강 정정 기간 동안 과목을 추가하거나 취소할 수 있습니다. 단, 정원 초과 과목의 경우 추가가 제한될 수 있습니다.",
    topic: "academic",
    createdAt: "2026-04-07T14:35:00Z",
    helpful: 38, notHelpful: 1, isNew: true,
  },
  {
    faqId: "5",
    question: "질병휴학 신청 시 어떤 서류가 필요한가요?",
    answer: "질병휴학은 전문의가 발급한 진단서가 필수입니다. 진단서에는 병명, 예상 치료 기간이 명시되어 있어야 하며, 학사지원처에 제출하거나 KLAS에 스캔본을 첨부해야 합니다. (학칙 제35조 ③호)",
    topic: "enrollment_status",
    createdAt: "2026-04-07T11:40:00Z",
    helpful: 34, notHelpful: 0, isNew: true,
  },
  {
    faqId: "6",
    question: "출석률이 낮으면 성적이 어떻게 되나요?",
    answer: "출석률이 75% 미만인 경우 해당 과목의 성적은 자동으로 F 처리됩니다. 지각은 결석의 1/3로 계산됩니다. (학칙 제42조 ⑤항)",
    topic: "academic",
    createdAt: "2026-04-07T09:30:00Z",
    helpful: 48, notHelpful: 5, isNew: true,
  },
  {
    faqId: "7",
    question: "졸업 요건 학점은 몇 학점인가요?",
    answer: "소속 학과에 따라 다르지만 일반적으로 총 130학점 이상 이수해야 합니다. 전공 필수 과목 이수, 교양 이수, 졸업논문 또는 졸업시험 통과 등이 함께 요구됩니다.",
    topic: "graduation",
    createdAt: "2026-04-06T15:50:00Z",
    helpful: 91, notHelpful: 2,
    sources: [
      { documentId: 17, documentTitle: "졸업요건 확인 안내", page: 1 },
      { documentId: 20, documentTitle: "SW융합대학 교육과정표 (2026학년도)", page: 12 },
    ] satisfies Source[],
  },
  {
    faqId: "8",
    question: "재수강 성적 상한이 있나요?",
    answer: "재수강 시 취득 성적이 B0을 초과하더라도 B0으로 표시됩니다. 재수강은 C+ 이하 성적을 취득한 동일 과목에 한해 1회만 허용됩니다. (학칙 제28조 ④항)",
    topic: "academic",
    createdAt: "2026-04-06T09:20:00Z",
    helpful: 61, notHelpful: 3,
  },
  {
    faqId: "9",
    question: "복수전공 신청 조건은 무엇인가요?",
    answer: "2학년 이상 재학생으로 직전 학기 GPA 2.5 이상, 취득 학점 30학점 이상인 경우 신청할 수 있습니다. 매 학기 개강 2주 전에 KLAS를 통해 신청하며, 학과별 인원 제한이 있을 수 있습니다.",
    topic: "curriculum",
    createdAt: "2026-04-05T11:00:00Z",
    helpful: 45, notHelpful: 2,
  },
  {
    faqId: "10",
    question: "국가장학금과 교내 장학금을 동시에 받을 수 있나요?",
    answer: "원칙적으로 중복 수혜가 제한될 수 있습니다. 국가장학금 수혜 금액에 따라 교내 장학금이 조정될 수 있으며, 세부 기준은 매 학기 학생지원처 공지를 확인해야 합니다.",
    topic: "scholarship",
    createdAt: "2026-04-05T08:45:00Z",
    helpful: 38, notHelpful: 4,
  },
  {
    faqId: "11",
    question: "예비 수강신청과 본 수강신청의 차이는?",
    answer: "예비 수강신청은 본 수강신청 전에 강좌 수요를 파악하기 위한 단계로, 예비 신청 결과가 본 수강신청에 자동 반영되지는 않습니다. 본 수강신청 기간에 다시 신청해야 합니다.",
    topic: "academic",
    createdAt: "2026-04-04T16:10:00Z",
    helpful: 55, notHelpful: 4,
  },
  {
    faqId: "12",
    question: "등록금 납부 기간을 놓치면 어떻게 되나요?",
    answer: "등록금 미납 시 미등록 제적 처리될 수 있습니다. 추납 기간이 별도로 공지되며, 추납 기간 내 납부하면 등록이 유지됩니다. 경제적 사정이 있는 경우 분할 납부를 신청할 수 있습니다.",
    topic: "registration",
    createdAt: "2026-04-04T10:00:00Z",
    helpful: 33, notHelpful: 2,
  },
  {
    faqId: "13",
    question: "부전공과 복수전공의 차이는?",
    answer: "복수전공은 졸업 시 두 개의 전공 학위가 표기되며 약 36~54학점을 이수해야 합니다. 부전공은 학위에 부전공으로 표기되며 약 21학점 이수가 필요합니다.",
    topic: "curriculum",
    createdAt: "2026-04-03T13:40:00Z",
    helpful: 52, notHelpful: 3,
  },
  {
    faqId: "14",
    question: "최대 몇 학기까지 휴학할 수 있나요?",
    answer: "군휴학을 제외하고 재학 중 통산 6학기까지 휴학 가능합니다. 연속으로는 최대 2학기까지만 허용되며, 초과 시 자동 제적 처리될 수 있습니다. (학칙 제35조 ②항)",
    topic: "enrollment_status",
    createdAt: "2026-04-03T10:05:00Z",
    helpful: 72, notHelpful: 2,
  },
  {
    faqId: "15",
    question: "현장실습 학점 인정 기준이 어떻게 되나요?",
    answer: "현장실습은 4주(160시간) 이상 수행 시 최소 3학점이 인정됩니다. 실습 기관은 학교와 협약이 체결된 곳이어야 하며, 실습 보고서와 기관 평가서를 제출해야 합니다.",
    topic: "career",
    createdAt: "2026-04-02T15:20:00Z",
    helpful: 29, notHelpful: 1,
  },
  {
    faqId: "16",
    question: "A 등급 비율 상한이 있나요?",
    answer: "상대평가 과목의 경우 A+(A0 포함) 등급의 비율은 수강자의 35%를 초과할 수 없습니다. 절대평가 과목이나 수강 인원이 10명 이하인 강좌는 예외입니다. (학칙 제42조 ③항)",
    topic: "academic",
    createdAt: "2026-04-02T11:15:00Z",
    helpful: 83, notHelpful: 6,
  },
  {
    faqId: "17",
    question: "조기졸업 조건은 무엇인가요?",
    answer: "GPA 4.0 이상을 유지하면서 졸업 요건 학점을 규정보다 1학기 이상 빠르게 이수한 경우 조기졸업이 가능합니다. 신청 전 학과 사무실 및 학사지원처에 문의하세요.",
    topic: "graduation",
    createdAt: "2026-04-01T10:30:00Z",
    helpful: 44, notHelpful: 1,
  },
  {
    faqId: "18",
    question: "자퇴 신청은 어떻게 하나요?",
    answer: "자퇴를 원하는 학생은 학과 사무실을 방문하여 자퇴원을 작성·제출해야 합니다. 미성년자의 경우 보호자(부모) 동의서가 필수이며, 등록금 환불은 학칙에 따라 시기별로 차등 적용됩니다.",
    topic: "enrollment_status",
    createdAt: "2026-03-30T14:20:00Z",
    helpful: 18, notHelpful: 1,
  },
  {
    faqId: "19",
    question: "학적 변동(전과) 신청은 어떻게 하나요?",
    answer: "전과 신청은 매 학년도 시작 전 공지되는 기간 내에 KLAS를 통해 신청합니다. 1학년 수료 이상, GPA 2.5 이상 등의 자격 요건이 있으며, 학과별 정원 범위 내에서 승인됩니다.",
    topic: "registration",
    createdAt: "2026-03-29T09:30:00Z",
    helpful: 25, notHelpful: 1,
  },
  {
    faqId: "20",
    question: "비교과 프로그램 참여 시 학점이 인정되나요?",
    answer: "비교과 프로그램은 학점으로 직접 인정되지 않지만, 마일리지 점수로 적립되어 장학금 선발 등에서 가산점으로 활용될 수 있습니다. 자세한 사항은 학생지원처에 문의해주세요.",
    topic: "event",
    createdAt: "2026-03-28T09:15:00Z",
    helpful: 21, notHelpful: 0,
  },
  {
    faqId: "21",
    question: "성적 증명서 발급은 어디서 하나요?",
    answer: "KLAS > 증명서 발급 메뉴 또는 학교 내 무인 증명서 발급기에서 발급 가능합니다. 영문 성적증명서도 동일하게 발급 가능하며, 졸업 후에도 발급할 수 있습니다.",
    topic: "other",
    createdAt: "2026-03-27T16:50:00Z",
    helpful: 35, notHelpful: 1,
  },
];
