// TODO: 실제 API 연동 시 제거

import type {
  AdminDocument,
  AdminStatistics,
  FAQCandidate,
} from "@/types/api/admin";
export const MOCK_ADMIN_STATISTICS: AdminStatistics = {
  overview: {
    totalQuestions: 12847,
    totalDocuments: 42,
    totalSessions: 8423,
    totalUsers: 1156,
  },
  users: {
    totalUsers: 12847,
    byUserType: { student: 10278, staff: 2569 },
    byDepartment: {
      software: 5243,
      ai: 3184,
    },
    byGrade: {
      "1": 3120,
      "2": 2980,
      "3": 2760,
      "4": 2030,
      "5_or_above": 1957,
    },
  },
  categories: [
    { category: "학사", questionCount: 3597, percentage: 28.0 },
    { category: "휴학·복학·자퇴", questionCount: 2226, percentage: 17.3 },
    { category: "졸업", questionCount: 1927, percentage: 15.0 },
    { category: "장학", questionCount: 1670, percentage: 13.0 },
    { category: "등록·학적", questionCount: 1156, percentage: 9.0 },
    { category: "전공·교과", questionCount: 899, percentage: 7.0 },
    { category: "취업·현장실습", questionCount: 642, percentage: 5.0 },
    { category: "행사·특강", questionCount: 385, percentage: 3.0 },
    { category: "기타", questionCount: 345, percentage: 2.7 },
  ],
};

export const MOCK_ADMIN_DOCUMENTS: AdminDocument[] = [
  {
    id: 1,
    title: "2024년도 학사요람.pdf",
    categoryId: 1,
    categoryName: "SW 학사공지",
    status: "completed",
    source: "KMU",
    createdAt: "2026-03-15T09:00:00Z",
  },
  {
    id: 2,
    title: "소프트웨어융합대학 교육과정표 2026.pdf",
    categoryId: 5,
    categoryName: "SW 졸업요건",
    status: "completed",
    source: "SW",
    createdAt: "2026-03-10T10:30:00Z",
  },
  {
    id: 3,
    title: "2026학년도 1학기 학사일정.pdf",
    categoryId: 6,
    categoryName: "국민대학교 공지",
    status: "completed",
    source: "KMU",
    createdAt: "2026-02-28T14:00:00Z",
  },
  {
    id: 4,
    title: "장학금 안내 및 신청서류.pdf",
    categoryId: 3,
    categoryName: "SW 장학공지",
    status: "processing",
    source: "KMU",
    createdAt: "2026-04-07T11:00:00Z",
  },
  {
    id: 5,
    title: "학칙 전문 (개정 2025.12).pdf",
    categoryId: 1,
    categoryName: "SW 학사공지",
    status: "completed",
    source: "KMU",
    createdAt: "2025-12-20T09:00:00Z",
  },
  {
    id: 6,
    title: "현장실습 운영 규정 개정안.pdf",
    categoryId: 2,
    categoryName: "SW 취업공지",
    status: "uploaded",
    source: "SW",
    createdAt: "2026-04-08T08:00:00Z",
  },
  {
    id: 7,
    title: "2025년도 수시 모집요강.pdf",
    categoryId: 6,
    categoryName: "국민대학교 공지",
    status: "failed",
    source: "KMU",
    createdAt: "2025-08-15T10:00:00Z",
  },
  {
    id: 8,
    title: "AI빅데이터융합경영학과 교육과정.pdf",
    categoryId: 5,
    categoryName: "SW 졸업요건",
    status: "reprocessing",
    source: "SW",
    createdAt: "2026-03-05T13:00:00Z",
  },
];

export const MOCK_FAQ_CANDIDATES: FAQCandidate[] = [
  {
    candidateId: "cand-001",
    question: "계절학기 수강신청은 언제 하나요?",
    source: "채팅 로그",
    status: "pending",
    createdAt: "2026-04-07T10:00:00Z",
    frequency: 23,
    topic: "academic",
    answerDraft:
      "계절학기 수강신청은 학기 종료 후 약 2주 뒤에 시작됩니다. 정확한 일정은 학사일정을 확인하세요.",
  },
  {
    candidateId: "cand-002",
    question: "졸업유예 신청 방법을 알고 싶어요.",
    source: "채팅 로그",
    status: "pending",
    createdAt: "2026-04-06T14:00:00Z",
    frequency: 18,
    topic: "graduation",
    answerDraft:
      "졸업유예는 KLAS에서 신청할 수 있으며, 졸업 예정 학기에 신청하시면 됩니다.",
  },
  {
    candidateId: "cand-003",
    question: "편입학 후 학점 인정 기준은 무엇인가요?",
    source: "채팅 로그",
    status: "pending",
    createdAt: "2026-04-05T09:30:00Z",
    frequency: 15,
    topic: "registration",
  },
  {
    candidateId: "cand-004",
    question: "학생증 재발급은 어디서 하나요?",
    source: "채팅 로그",
    status: "rejected",
    createdAt: "2026-04-04T11:00:00Z",
    frequency: 12,
    topic: "other",
    answerDraft:
      "학생증 재발급은 학생처에 방문하시거나 온라인으로 신청하실 수 있습니다.",
  },
  {
    candidateId: "cand-005",
    question: "공학인증 요건이 어떻게 되나요?",
    source: "채팅 로그",
    status: "pending",
    createdAt: "2026-04-03T15:00:00Z",
    frequency: 11,
    topic: "curriculum",
  },
  {
    candidateId: "cand-006",
    question: "교환학생 신청 자격과 절차를 알고 싶어요.",
    source: "채팅 로그",
    status: "registered",
    createdAt: "2026-04-02T13:00:00Z",
    frequency: 9,
    topic: "academic",
    answerDraft:
      "교환학생 신청은 학교 홈페이지를 통해 신청하실 수 있습니다. 어학 성적 등 자격 요건이 있으니 공고문을 확인하세요.",
  },
  {
    candidateId: "cand-007",
    question: "논문 제출 기준이 어떻게 되나요?",
    source: "채팅 로그",
    status: "pending",
    createdAt: "2026-04-01T10:00:00Z",
    frequency: 8,
    topic: "graduation",
  },
];

