import type { AdminUserItem } from '@/types/api/admin';

export const MOCK_ADMIN_USERS: AdminUserItem[] = [
  {
    id: 1,
    name: '김민수',
    email: 'minsu.kim@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 30,
    todayUsed: 15,
  },
  {
    id: 2,
    name: '이서연',
    email: 'seoyeon.lee@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 30,
    todayUsed: 28,
  },
  {
    id: 3,
    name: '박지훈',
    email: 'jihoon.park@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 30,
    todayUsed: 30,
  },
  {
    id: 4,
    name: '정하은',
    email: 'haeun.jung@kookmin.ac.kr',
    userType: 'student',
    role: 'admin',
    dailyChatLimit: 50,
    todayUsed: 5,
  },
  {
    id: 5,
    name: '최영호',
    email: 'youngho.choi@kookmin.ac.kr',
    userType: 'staff',
    role: 'user',
    dailyChatLimit: 50,
    todayUsed: 0,
  },
  {
    id: 6,
    name: '강수진',
    email: 'sujin.kang@kookmin.ac.kr',
    userType: 'staff',
    role: 'admin',
    dailyChatLimit: 50,
    todayUsed: 12,
  },
  {
    id: 7,
    name: '윤재현',
    email: 'jaehyun.yoon@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 20,
    todayUsed: 0,
  },
  {
    id: 8,
    name: '한소희',
    email: 'sohee.han@kookmin.ac.kr',
    userType: 'staff',
    role: 'user',
    dailyChatLimit: 30,
    todayUsed: 5,
  },
  {
    id: 9,
    name: '오준서',
    email: 'junseo.oh@kookmin.ac.kr',
    userType: 'student',
    role: 'user',
    dailyChatLimit: 20,
    todayUsed: 18,
  },
  {
    id: 10,
    name: '임도윤',
    email: 'doyoon.lim@kookmin.ac.kr',
    userType: 'staff',
    role: 'admin',
    dailyChatLimit: 50,
    todayUsed: 45,
  },
];

export const MOCK_DEFAULT_CHAT_LIMIT = 30;
